# Generated by Django 5.2.1 on 2025-05-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitoredwebsite_monitoringresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredwebsite')),
            ],
        ),
    ]
