# Generated by Django 5.2.1 on 2025-06-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_percent', models.FloatField()),
                ('ram_used', models.IntegerField()),
                ('ram_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField()),
                ('is_up', models.BooleanField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredwebsite')),
            ],
        ),
    ]
