# Generated by Django 5.2.1 on 2025-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredwebsite',
            name='last_status',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
