# Generated by Django 5.2.1 on 2025-06-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_monitoredwebsite_last_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sshmetric',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.sshhost'),
        ),
    ]
