# Generated by Django 5.2.1 on 2025-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_sshhost_alter_sshmetric_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshhost',
            name='name',
        ),
        migrations.AlterField(
            model_name='sshhost',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
    ]
