# Generated by Django 5.2.1 on 2025-06-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_sshhost_name_alter_sshhost_hostname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UptimeCheck',
        ),
    ]
